python/PIL-CVE-2018-16509/Dockerfile, python/PIL-CVE-2018-16509/README.md, python/PIL-CVE-2018-16509/app.py, python/PIL-CVE-2018-16509/docker-compose.yml, python/PIL-CVE-2018-16509/rce.jpg
Similar with the one with PIL-CVE-2017-8291 but this one is using the vulnerability from https://seclists.org/oss-sec/2018/q3/142
=> Add PIL-CVE-2018-16509

flask/ssti/docker-compose.yml
=> Update flask-ssti docker-compose.yml

ghostscript/CVE-2018-19475/poc.png
"poc.png" was missing in the folder. I've added it back using the command listed in the screenshot and README.
=> Add missing poc.png

coldfusion/CVE-2017-3066/README.md, jboss/CVE-2017-12149/README.md, log4j/CVE-2017-5645/README.md, spring/CVE-2016-4977/README.md, spring/CVE-2017-8046/README.md
Domain was changed in README.md.
Before:  
`http://jackson.thuraisamy.me/runtime-exec-payloads.html`
After:  
`http://www.jackson-t.ca/runtime-exec-payloads.html`
=> Fix link for runtime-exec-payloads.html

README.md, README.zh-cn.md
=> Sponsor community

base/jboss/as-4.0.5/Dockerfile, base/jboss/as-6.1.0/Dockerfile, jboss/CVE-2017-7504/README.md
=> [Bug] fixed for JBoss #248 

README.md, README.zh-cn.md
Welcome a new sponser: <https://www.huoxian.cn>
=> Welcome a new sponser: Huoxian

dubbo/CVE-2019-17564/README.md, dubbo/CVE-2019-17564/README.zh-cn.md
"CommonsBeanutils6" is wrong, change to "CommonsCollections6"
=> fix dubbo cve-2019-17564 ysoserial generate payload error

jumpserver/CVE-2023-42820/README.md, jumpserver/CVE-2023-42820/README.zh-cn.md, jumpserver/CVE-2023-42820/docker-compose.yml
Add documentation to resolve #467
=> added DOMAINS description for manual

django/CVE-2022-34265/README.md, django/CVE-2022-34265/README.zh-cn.md
Hi @phith0n the objective of this PR is so that we can _see how to fix the vulnerability_. What do you think?
=> Add Django commit to fix CVE-2022-34265

neo4j/CVE-2021-34371/rhino_gadget/pom.xml
neo4j - Fixed javassist error (invalid constant type: 18)
=> Update Neo4j Shell Server pom.xml

environments.toml, gitea/1.4-rce/README.md, gitea/1.4-rce/README.zh-cn.md, gitea/1.4-rce/docker-compose.yml
=> [translate] Gitea 1.4.0 Directory Traversal Leading to Remote Command Execution

drupal/CVE-2014-3704/README.md, drupal/CVE-2014-3704/README.zh-cn.md, drupal/CVE-2017-6920/README.md, drupal/CVE-2017-6920/README.zh-cn.md, drupal/CVE-2018-7600/README.md, drupal/CVE-2018-7600/README.zh-cn.md, drupal/CVE-2018-7602/README.md, drupal/CVE-2018-7602/README.zh-cn.md, drupal/CVE-2019-6339/README.md, drupal/CVE-2019-6339/README.zh-cn.md, drupal/CVE-2019-6341/README.md, drupal/CVE-2019-6341/README.zh-cn.md, environments.toml
- Update English and Chinese README files with official references
- Enhance vulnerability description and context
- Improve readability and translation consistency
=> Improve README for Drupal issues

base/drupal/8.3.0/Dockerfile, drupal/CVE-2014-3704/docker-compose.yml, drupal/CVE-2017-6920/docker-compose.yml, drupal/CVE-2018-7600/README.md, drupal/CVE-2018-7600/README.zh-cn.md, drupal/CVE-2018-7600/docker-compose.yml, drupal/CVE-2018-7602/README.md, drupal/CVE-2018-7602/README.zh-cn.md, drupal/CVE-2018-7602/docker-compose.yml, drupal/CVE-2019-6339/docker-compose.yml, drupal/CVE-2019-6341/docker-compose.yml, environments.toml
- Create Dockerfile for Drupal 8.3.0 base image with YAML extension
- Update docker-compose files for Drupal CVE-2014-3704 and CVE-2017-6920
- Remove version specification in docker-compose files
- Use vulhub/drupal image for consistent environment setup
=> Improve Drupal environments

environments.toml, solr/CVE-2017-12629-RCE/README.md, solr/CVE-2017-12629-RCE/README.zh-cn.md, solr/CVE-2017-12629-RCE/docker-compose.yml, solr/CVE-2017-12629-XXE/README.zh-cn.md, solr/CVE-2017-12629-XXE/docker-compose.yml, solr/CVE-2019-0193/README.zh-cn.md, solr/CVE-2019-0193/docker-compose.yml, solr/CVE-2019-17558/README.md, solr/CVE-2019-17558/README.zh-cn.md, solr/CVE-2019-17558/docker-compose.yml, solr/Remote-Streaming-Fileread/README.md, solr/Remote-Streaming-Fileread/README.zh-cn.md, solr/Remote-Streaming-Fileread/docker-compose.yml
- Add Chinese version README
- Remove Docker Compose version specification
- Improve documentation clarity and language
=> Update Apache Solr vulnerabilities documentation

.cursor/rules/vulhub.mdc, environments.toml, ghostscript/CVE-2018-16509/README.md, ghostscript/CVE-2018-16509/README.zh-cn.md, ghostscript/CVE-2018-16509/docker-compose.yml, ghostscript/CVE-2018-19475/README.md, ghostscript/CVE-2018-19475/README.zh-cn.md, ghostscript/CVE-2018-19475/docker-compose.yml, ghostscript/CVE-2019-6116/README.md, ghostscript/CVE-2019-6116/README.zh-cn.md, ghostscript/CVE-2019-6116/docker-compose.yml
- Add Chinese version README (README.zh-cn.md)
- Refine environment name in environments.toml
- Improve documentation clarity and language
=> Update GhostScript issues documentation

environments.toml, php/CVE-2012-1823/README.md, php/CVE-2012-1823/README.zh-cn.md, php/CVE-2012-1823/docker-compose.yml, php/CVE-2018-19518/README.md, php/CVE-2018-19518/README.zh-cn.md, php/CVE-2018-19518/docker-compose.yml, php/CVE-2019-11043/README.md, php/CVE-2019-11043/README.zh-cn.md, php/CVE-2019-11043/docker-compose.yml, php/fpm/README.md, php/fpm/README.zh-cn.md, php/fpm/docker-compose.yml, php/php_xxe/README.md, php/php_xxe/README.zh-cn.md, php/php_xxe/docker-compose.yml, php/xdebug-rce/README.md, php/xdebug-rce/README.zh-cn.md
- Add Chinese version README (README.zh-cn.md)
- Remove Docker Compose version specification
- Improve documentation clarity and technical details
- Add more comprehensive explanation of vulnerability mechanism
=> Update PHP issues documentation

discuz/wooyun-2010-080723/README.md, discuz/wooyun-2010-080723/README.zh-cn.md, discuz/wooyun-2010-080723/docker-compose.yml, discuz/x3.4-arbitrary-file-deletion/README.md, discuz/x3.4-arbitrary-file-deletion/README.zh-cn.md, discuz/x3.4-arbitrary-file-deletion/docker-compose.yml, environments.toml
- Rename environment in environments.toml to clarify vulnerability type
- Remove Docker Compose version specification
- Add Chinese version README (README.zh-cn.md)
- Enhance documentation with detailed technical explanation of remote code execution vulnerability
=> Update Discuz vulnerabilities documentation

ecshop/collection_list-sqli/README.zh-cn.md, ecshop/collection_list-sqli/docker-compose.yml
- Add Chinese version README (README.zh-cn.md)
- Remove Docker Compose version specification
- Enhance documentation with detailed explanation of ECShop collection_list SQL injection vulnerability
=> Add Chinese translation and improve ECShop SQL injection documentation

tests/check/test_translate.py, tests/image-build.sh
- Create new test script to check for missing Chinese translations
- Implement test_translate() function to validate README translations
- Add error reporting for directories missing Chinese README files
- Improve project documentation consistency
=> Ensure all manual translated

environments.toml, tests/check/test_env_toml.py
- Introduced a comprehensive tags section for each vulnerability to categorize them by type, such as RCE, Auth Bypass, and SQL Injection.
- Updated test_env_toml.py to validate the presence of the new 'tags' field and ensure it contains valid entries.
=> Enhance environments.toml with tags

jenkins/CVE-2017-1000353/README.md, jenkins/CVE-2017-1000353/README.zh-cn.md, tests/markdownlint.json
=> Update README files for CVE-2017-1000353 to include Java version recommendation
